version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: nestjs_bg_template_api
    container_name: nestjs_bg_template_container
    command: [sh, -c, "cd /usr/src/app npx prisma migrate dev && yarn run start:dev"]
    ports:
      - 6541:6541
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app
    # environment:
    #   NODE_ENV: productions

# networks:
#   backend-server:
    
